# Generated by Django 5.1.4 on 2024-12-18 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_assignment_completed_tasks_assignment_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='base.project'),
        ),
    ]
